### ISSUE TITLE
feat: add hooks for running scripts before and after link

### ISSUE THREAD

**Issue by cristianoliveira** [cristianoliveira/pono#23]
I got this requirement while using stow to configure git. There is a file in my dotfiles that I generate `~/.gitconfig.user` with a script, so with pono I wanted to be able to run such script before linking or (during link)

```toml
[ponos]
git = { ... before_execute='script/or path to executable' }
````
